/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zfzhao_myappdemo_MainActivity */

#ifndef _Included_com_zfzhao_myappdemo_MainActivity
#define _Included_com_zfzhao_myappdemo_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zfzhao_myappdemo_MainActivity
 * Method:    getJniStr
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_zfzhao_myappdemo_MainActivity_getJniStr
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
